export PA_DIR := $(LEGATO_ROOT)/platformAdaptor
export LEGATO_AUDIO_PA_AMR =
export LEGATO_AUDIO_PA_PCM =
export LEGATO_MODEM_PA_ECALL =
export LEGATO_AUDIO_PA_DEFAULT = $(LEGATO_ROOT)/components/audio/platformAdaptor/default/le_pa_audio_default
export LEGATO_AUDIO_PA_AMR_DEFAULT = $(LEGATO_ROOT)/components/audio/platformAdaptor/default/le_pa_amr_default
export LEGATO_AUDIO_PA_PCM_DEFAULT = $(LEGATO_ROOT)/components/audio/platformAdaptor/default/le_pa_pcm_default
export LEGATO_AVC_PA_DEFAULT = $(LEGATO_ROOT)/components/airVantage/platformAdaptor/default/le_pa_avc_default
export LEGATO_GNSS_PA_DEFAULT = $(LEGATO_ROOT)/components/positioning/platformAdaptor/default/le_pa_gnss_default
export LEGATO_MODEM_PA_DEFAULT = $(LEGATO_ROOT)/components/modemServices/platformAdaptor/default/le_pa_default
export LEGATO_MODEM_PA_ECALL_DEFAULT = $(LEGATO_ROOT)/components/modemServices/platformAdaptor/default/le_pa_ecall_default
export LEGATO_SECSTORE_PA_DEFAULT = $(LEGATO_ROOT)/components/secStore/platformAdaptor/default/le_pa_secStore_default
export LEGATO_FWUPDATE_PA_DEFAULT = $(LEGATO_ROOT)/components/fwupdate/platformAdaptor/default/le_pa_fwupdate_default
export LEGATO_UARTMODE_PA_DEFAULT = $(LEGATO_ROOT)/components/uartMode/platformAdaptor/default/le_pa_uartMode_default
